export const prductConfig={
    subTitle:" Have a Look Over The Products",
    title:"Our Range Of Products",
    productsList:[
        {
            id:1,
            productName:"Mustard Oil",
            category:"Ayurvedic Hair oil",
            productDecscUrl:"/Mustard.jpg",
            href:"/",
            mrpPrice:"160",
            sellPrice:"140",
            currency:"INR",
            details:"View Details",
        },
        {
            id:2,
            productName:"Amla oil",
            category:"Ayurvedic Hair oil",
            productDecscUrl:"/amla.jpg",
            href:"/",
            mrpPrice:"160",
            sellPrice:"100",
            currency:"INR",
            details:"View Details",
            navTitle:"Products",

        },
        {
            id:3,
            productName:"Neem Oil",
            category:"Ayurvedic Hair oil",
            productDecscUrl:"/neem.jpg",
            href:"/",
            mrpPrice:"160",
            sellPrice:"180",
            currency:"INR",
            details:"View Details",
            navTitle:"Products",
        },
        {
            id:4,
            productName:"Aloe Vera Oil",
            category:"Ayurvedic Hair oil",
            productDecscUrl:"/aloe-vera.jpg",
            href:"/",
            mrpPrice:"160",
            sellPrice:"120",
            currency:"INR",
            details:"View Details",
            navTitle:"Products",
        },
        {
            id:5,
            productName:"Neem Oil",
            category:"Ayurvedic Hair oil",
            productDecscUrl:"/neem.jpg",
            href:"/",
            mrpPrice:"160",
            sellPrice:"180",
            currency:"INR",
            details:"View Details",
            navTitle:"Products",
        },
        {
            id:6,
            productName:"Aloe Vera Oil",
            category:"Ayurvedic Hair oil",
            productDecscUrl:"/aloe-vera.jpg",
            href:"/",
            mrpPrice:"160",
            sellPrice:"120",
            currency:"INR",
            details:"View Details",
            navTitle:"Products",
        },
        {
            id:7,
            productName:"Neem Oil",
            category:"Ayurvedic Hair oil",
            productDecscUrl:"/neem.jpg",
            href:"/",
            mrpPrice:"160",
            sellPrice:"180",
            currency:"INR",
            details:"View Details",
            navTitle:"Products",
        },
        {
            id:8,
            productName:"Aloe Vera Oil",
            category:"Ayurvedic Hair oil",
            productDecscUrl:"/aloe-vera.jpg",
            href:"/",
            mrpPrice:"160",
            sellPrice:"120",
            currency:"INR",
            details:"View Details",
            navTitle:"Products",
        }
    ]
}